### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by pi198pi** [ArkAngeL43/Red-Rabbit#2]
Traceback (most recent call last):
        2: from main.rb:333:in `<main>'
        1: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- packetgen (LoadError)

i got this when i try to run sudo ruby main.rb

**Comment by TotallyNotAHaxxer** [comment]
you have to run the install file, when you run it and still get the error and ruby says "can not load gem" run the following install 
sudo gem install <gem name> in this case -> sudo gem install packetgen
